apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "shubhamstore.fullname" . }}-redis
  labels:
    {{- include "shubhamstore.labels" . | nindent 4 }}
    app.kubernetes.io/component: cache
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "shubhamstore.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: cache
  template:
    metadata:
      labels:
        {{- include "shubhamstore.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: cache
    spec:
      containers:
      - name: redis
        image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
        command: ["redis-server", "--appendonly", "yes"]
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redis-data
          mountPath: /data
        resources:
          {{- toYaml .Values.redis.resources | nindent 10 }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          runAsNonRoot: true
          runAsUser: 999
      volumes:
      - name: redis-data
        persistentVolumeClaim:
          claimName: {{ include "shubhamstore.fullname" . }}-redis-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "shubhamstore.fullname" . }}-redis-pvc
  labels:
    {{- include "shubhamstore.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "shubhamstore.fullname" . }}-redis
  labels:
    {{- include "shubhamstore.labels" . | nindent 4 }}
    app.kubernetes.io/component: cache
spec:
  type: ClusterIP
  selector:
    {{- include "shubhamstore.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: cache
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
